stages:
  - build

build:
  stage: build
  image: golang:1.16

  script:
    - mkdir -p bin
    - GOOS=linux GOARCH=amd64 go build -o bin/butler-linux-amd64
    - GOOS=linux GOARCH=arm64 go build -o bin/butler-linux-arm64
    - GOOS=windows GOARCH=amd64 go build -o bin/butler-windows-amd64.exe
    - GOOS=darwin GOARCH=amd64 go build -o bin/butler-darwin-amd64

  after_script:
    - |
      git config --global user.email "ci@gitlab.com"
      git config --global user.name "GitLab CI"
      git add bin/
      git commit -m "Add build artifacts"
      git push

  artifacts:
    paths:
      - bin/
