name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build and package
      run: |
        mkdir -p bin
        GOOS=linux GOARCH=amd64 go build -o bin/butler-linux-amd64
        GOOS=linux GOARCH=arm64 go build -o bin/butler-linux-arm64
        GOOS=windows GOARCH=amd64 go build -o bin/butler-windows-amd64.exe
        GOOS=darwin GOARCH=amd64 go build -o bin/butler-darwin-amd64

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: bin/

    - name: Commit and push binaries
      run: |
        git remote add gh git@github.com:williamotieno/butler.git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add bin/
        git commit -m "Add build artifacts" || true
        git push gh || true
